workflows:
  sid-android-release:
    name: Sid APK Build
    environment:
      flutter: stable
    scripts:
      - name: Check Flutter setup
        script: |
          flutter --version
          flutter doctor
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      scripts:
        - echo "📦 SID APK build complete!"

